-- Retroactive migration — chatbot tables (RAG).
--
-- Originally shipped as the loose `manual_create_chatbot_tables.sql` patch
-- on 2026-01-29. That file used UUID columns with gen_random_uuid() defaults,
-- but prod was actually bootstrapped via Prisma's `db push` against the
-- Prisma schema, so the real columns are TEXT with UUIDs generated by the
-- client. This migration reproduces the prod shape so a fresh dev DB
-- matches; prod has this migration already marked as `applied` via
-- `prisma migrate resolve --applied`.
--
-- All `IF NOT EXISTS` / DO-block guards are retained so applying the
-- migration a second time is a no-op.

-- ============================================
-- TABLE: chat_conversations
-- ============================================
CREATE TABLE IF NOT EXISTS "chat_conversations" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "videoId" TEXT,
    "courseId" TEXT,
    "title" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "chat_conversations_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "chat_conversations_userId_idx" ON "chat_conversations"("userId");
CREATE INDEX IF NOT EXISTS "chat_conversations_videoId_idx" ON "chat_conversations"("videoId");
CREATE INDEX IF NOT EXISTS "chat_conversations_courseId_idx" ON "chat_conversations"("courseId");
CREATE INDEX IF NOT EXISTS "chat_conversations_createdAt_idx" ON "chat_conversations"("createdAt");

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chat_conversations_userId_fkey'
    ) THEN
        ALTER TABLE "chat_conversations"
            ADD CONSTRAINT "chat_conversations_userId_fkey"
            FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
END$$;

-- ============================================
-- TABLE: chat_messages
-- ============================================
CREATE TABLE IF NOT EXISTS "chat_messages" (
    "id" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "sources" JSONB,
    "tokenCount" INTEGER,
    "feedback" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "chat_messages_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "chat_messages_conversationId_idx" ON "chat_messages"("conversationId");
CREATE INDEX IF NOT EXISTS "chat_messages_createdAt_idx" ON "chat_messages"("createdAt");

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chat_messages_conversationId_fkey'
    ) THEN
        ALTER TABLE "chat_messages"
            ADD CONSTRAINT "chat_messages_conversationId_fkey"
            FOREIGN KEY ("conversationId") REFERENCES "chat_conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
END$$;

-- ============================================
-- TABLE: transcript_embeddings
-- (pgvector column is added by a later migration, not here.)
-- ============================================
CREATE TABLE IF NOT EXISTS "transcript_embeddings" (
    "id" TEXT NOT NULL,
    "videoId" TEXT NOT NULL,
    "chunkIndex" INTEGER NOT NULL,
    "chunkText" TEXT NOT NULL,
    "startTime" DOUBLE PRECISION NOT NULL,
    "endTime" DOUBLE PRECISION NOT NULL,
    "embeddingId" TEXT,
    "isIndexed" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "transcript_embeddings_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "transcript_embeddings_videoId_idx" ON "transcript_embeddings"("videoId");
CREATE INDEX IF NOT EXISTS "transcript_embeddings_isIndexed_idx" ON "transcript_embeddings"("isIndexed");

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'transcript_embeddings_videoId_chunkIndex_key'
    ) THEN
        ALTER TABLE "transcript_embeddings"
            ADD CONSTRAINT "transcript_embeddings_videoId_chunkIndex_key"
            UNIQUE ("videoId", "chunkIndex");
    END IF;
END$$;
